spring.application.name=Maven0915
server.port=9090
servlet.servlet.context-path=/hym

spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=jdbc:sqlserver://localhost:1433;database=master;sslProtocol=TLS;Encrypt=false
spring.datasource.username=sa
spring.datasource.password=ll367115
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver